---
kind: pipeline
type: docker
name: learn-app-development

environment:
  namespace: default

clone:
  depth: 50

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
      - rm -f .tags
      - printf "%s\n" $(git describe --abbrev=0 --tags || echo $DRONE_BRANCH | tr '/' '-') > .tags
      - printf "Tags to build\n-------------\n%s\n" $(cat .tags)

  - name: Run chart-testing (lint)
    image: dxas90/drone-helper
    commands:
      - sh -c "ct lint --config test/chart-testing.yaml"
    depends_on:
      - fetch

  - name: UnitTest (test)
    image: golang
    commands:
      - go test
      - go build
    depends_on:
      - fetch

  - name: Go image (build)
    image: banzaicloud/drone-kaniko
    settings:
      skip_tls_verify: false # set to true for testing registries ONLY with self-signed certs
      build_args:
        - COMMIT_SHA=${DRONE_COMMIT_SHA}
        - COMMIT_AUTHOR_EMAIL=${DRONE_COMMIT_AUTHOR_EMAIL}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: dxas90/learn
      dockerfile: Dockerfile
      registry: harbor.dxas90.xyz
    depends_on:
      - Run chart-testing (lint)
      - UnitTest (test)

  - name: Run Kustomize
    image: dxas90/drone-helper
    commands:
      - sh -c "cd k8s; kustomize edit set image dxas90/learn:$(git describe --abbrev=0 --tags)"
    depends_on:
      - Go image (build)
    when:
      branch:
        - develop

trigger:
  event:
    - push
---
kind: pipeline
type: docker
name: learn-app-release

environment:
  namespace: default

clone:
  depth: 50

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags

  - name: Run Kustomize
    image: dxas90/drone-helper
    commands:
      - sh -c "cd k8s; kustomize edit set image dxas90/learn:$(git describe --abbrev=0 --tags)"

trigger:
  branch:
    - master
  event:
    - tag
