kind: pipeline
type: docker
name: learn-app-test-build

environment:
  namespace: default

clone:
  depth: 50

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
      - rm -f .tags

  - name: UnitTest (test)
    image: golang
    commands:
      - go test -v
      - go build
    depends_on:
      - fetch
    when:
      event:
        include:
          - push
          - pull_request

  - name: Run chart-testing (lint)
    image: dxas90/drone-helper:v0.3.0
    commands:
      - sh -c "ct lint --config test/chart-testing.yaml"
    depends_on:
      - fetch
    when:
      event:
        include:
          - push
          - pull_request

  - name: Build helm chart (build)
    image: dxas90/drone-helper:v0.3.0
    environment:
      APP_VERSION: 1.0.${DRONE_BUILD_NUMBER} # TODO
      CHART_VERSION: 1.0.${DRONE_BUILD_NUMBER}
    commands:
      - sh -c "envsubst < charts/learn/Chart.yaml.tmpl | cat > charts/learn/Chart.yaml"
      - sh -c "tar czf /tmp/chart${DRONE_BUILD_NUMBER}.tgz -C charts/learn/ ."
    depends_on:
      - fetch
    when:
      event:
        include:
          - push
          - pull_request

  - name: Publish helm chart (publish)
    image: dxas90/drone-helper:v0.3.0
    environment:
      USERNAME:
        from_secret: helm_username
      PASSWORD:
        from_secret: helm_password
      REPO:
        from_secret: helm_repo
    commands:
      - sh -c curl --user "${USERNAME}:${PASSWORD}" -X POST --upload-file /tmp/chart${DRONE_BUILD_NUMBER}.tgz ${REPO}/api/packages/${USERNAME}/helm/api/charts'
    depends_on:
      - Run chart-testing (lint)
    when:
      event:
        include:
          - push

  - name: build branch image (build)
    image: plugins/kaniko
    settings:
      build_args:
        - COMMIT_SHA=${DRONE_COMMIT_SHA}
        - COMMIT_AUTHOR_EMAIL=${DRONE_COMMIT_AUTHOR_EMAIL}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_BRANCH//\//_}-${DRONE_BUILD_NUMBER}-branch
      repo: gitea.dxas90.xyz/${DRONE_REPO_NAMESPACE,,}/${DRONE_REPO_NAME,,}
      registry: gitea.dxas90.xyz
      expand-repo: false
    depends_on:
      - Run chart-testing (lint)
      - UnitTest (test)
    when:
      branch:
        - feature/*
        - hotfix/*
        - bugfix/*
        - develop
      event:
        - push

  - name: build staging image (build)
    image: plugins/kaniko
    settings:
      build_args:
        - COMMIT_SHA=${DRONE_COMMIT_SHA}
        - COMMIT_AUTHOR_EMAIL=${DRONE_COMMIT_AUTHOR_EMAIL}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
      repo: gitea.dxas90.xyz/${DRONE_REPO_NAMESPACE,,}/${DRONE_REPO_NAME,,}
      registry: gitea.dxas90.xyz
      expand-repo: false
    depends_on:
      - Run chart-testing (lint)
      - UnitTest (test)
    when:
      branch:
        - master
      event:
        - push

  - name: build production image (build)
    image: plugins/kaniko
    settings:
      build_args:
        - COMMIT_SHA=${DRONE_COMMIT_SHA}
        - COMMIT_AUTHOR_EMAIL=${DRONE_COMMIT_AUTHOR_EMAIL}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_TAG}
      repo: gitea.dxas90.xyz/${DRONE_REPO_NAMESPACE,,}/${DRONE_REPO_NAME,,}
      registry: gitea.dxas90.xyz
      expand-repo: false
    depends_on:
      - build staging image (build)
    when:
      event:
        - tag
