kind: pipeline
type: docker
name: learn-app-development

environment:
  namespace: default

clone:
  depth: 50

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
      - rm -f .tags

  - name: Run chart-testing (lint)
    image: dxas90/drone-helper
    commands:
      - sh -c "ct lint --config test/chart-testing.yaml"
    depends_on:
      - fetch
    when:
      branch:
        include:
          - feature/*
          - master
          - develop
      event:
        include:
          - push
          - pull_request

  - name: UnitTest (test)
    image: golang
    commands:
      - go test
      - go build
    depends_on:
      - fetch
    when:
      branch:
        include:
          - feature/*
          - master
          - develop
      event:
        include:
          - push
          - pull_request

  - name: build branch image (build)
    image: banzaicloud/drone-kaniko
    settings:
      skip_tls_verify: false # set to true for testing registries ONLY with self-signed certs
      build_args:
        - COMMIT_SHA=${DRONE_COMMIT_SHA}
        - COMMIT_AUTHOR_EMAIL=${DRONE_COMMIT_AUTHOR_EMAIL}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tag:
        - ${DRONE_BRANCH##feature/}
      repo: dxas90/learn
      dockerfile: Dockerfile
      registry: harbor.dxas90.xyz
    depends_on:
      - Run chart-testing (lint)
      - UnitTest (test)
    when:
      branch:
        - feature/*
      event:
        - push

  - name: build test image (build)
    image: banzaicloud/drone-kaniko
    settings:
      skip_tls_verify: false # set to true for testing registries ONLY with self-signed certs
      build_args:
        - COMMIT_SHA=${DRONE_COMMIT_SHA}
        - COMMIT_AUTHOR_EMAIL=${DRONE_COMMIT_AUTHOR_EMAIL}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tag:
        - test
      repo: dxas90/learn
      dockerfile: Dockerfile
      registry: harbor.dxas90.xyz
    depends_on:
      - Run chart-testing (lint)
      - UnitTest (test)
    when:
      branch:
        - develop
      event:
        - push

  - name: build staging image (build)
    image: banzaicloud/drone-kaniko
    settings:
      skip_tls_verify: false # set to true for testing registries ONLY with self-signed certs
      build_args:
        - COMMIT_SHA=${DRONE_COMMIT_SHA}
        - COMMIT_AUTHOR_EMAIL=${DRONE_COMMIT_AUTHOR_EMAIL}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tag:
        - latest
      repo: dxas90/learn
      dockerfile: Dockerfile
      registry: harbor.dxas90.xyz
    depends_on:
      - Run chart-testing (lint)
      - UnitTest (test)
    when:
      branch:
        - master
      event:
        - pull_request

  - name: build production image (build)
    image: banzaicloud/drone-kaniko
    settings:
      skip_tls_verify: false # set to true for testing registries ONLY with self-signed certs
      build_args:
        - COMMIT_SHA=${DRONE_COMMIT_SHA}
        - COMMIT_AUTHOR_EMAIL=${DRONE_COMMIT_AUTHOR_EMAIL}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tag:
        - ${DRONE_TAG}
      repo: dxas90/learn
      dockerfile: Dockerfile
      registry: harbor.dxas90.xyz
    depends_on:
      - Run chart-testing (lint)
      - UnitTest (test)
    when:
      event:
        - tag
