---
kind: pipeline
type: docker
name: golang

environment:
  LAST_COMMIT_HASH: "$${DRONE_COMMIT_SHA::7}"

clone:
  depth: 50

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
      - printf "go-%s" $(git describe --tags --always --dirty) > .tags

  - name: build Go image
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build --no-cache -t "${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}:$(cat .tags)" -f docker/go.dockerfile .
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
trigger:
  branch:
    - master
    - feature/*
  event:
    - push
---
kind: pipeline
type: docker
name: node

environment:
  LAST_COMMIT_HASH: "$${DRONE_COMMIT_SHA::7}"

clone:
  depth: 50

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
      - printf "node-%s" $(git describe --tags --always --dirty) > .tags

  - name: build Node image
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build --no-cache -t "${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}:$(cat .tags)" -f docker/node.dockerfile .
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
trigger:
  branch:
    - master
    - feature/*
  event:
    - push

---
kind: pipeline
type: docker
name: python

environment:
  LAST_COMMIT_HASH: "$${DRONE_COMMIT_SHA::7}"

clone:
  depth: 50

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
      - printf "python-%s" $(git describe --tags --always --dirty) > .tags

  - name: build Python image
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build --no-cache -t "${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}:$(cat .tags)" -f docker/python.dockerfile .
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
trigger:
  branch:
    - master
    - feature/*
  event:
    - push

---
kind: pipeline
type: docker
name: java

environment:
  LAST_COMMIT_HASH: "$${DRONE_COMMIT_SHA::7}"

clone:
  depth: 50

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
      - printf "java-%s" $(git describe --tags --always --dirty) > .tags

  - name: build Java image
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build --no-cache -t "${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}:$(cat .tags)" -f docker/java.dockerfile .
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
trigger:
  branch:
    - master
    - feature/*
  event:
    - push
