kind: pipeline
type: docker
name: learn-app-development

environment:
  namespace: default

clone:
  depth: 50

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
      - rm -f .tags

  - name: Run chart-testing (lint)
    image: dxas90/drone-helper:v0.0.3
    commands:
      - sh -c "ct lint --config test/chart-testing.yaml"
    depends_on:
      - fetch
    when:
      event:
        include:
          - push
          - pull_request

  - name: UnitTest (test)
    image: golang
    commands:
      - go test -v
      - go build
    depends_on:
      - fetch
    when:
      event:
        include:
          - push
          - pull_request

  - name: build branch image (build)
    image: plugins/kaniko
    settings:
      build_args:
        - COMMIT_SHA=${DRONE_COMMIT_SHA}
        - COMMIT_AUTHOR_EMAIL=${DRONE_COMMIT_AUTHOR_EMAIL}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_BRANCH//\//_}-${DRONE_BUILD_NUMBER}-branch
      repo: gitea.dxas90.xyz/dxas90/learn
      registry: gitea.dxas90.xyz
      expand-repo: false
    depends_on:
      - Run chart-testing (lint)
      - UnitTest (test)
    when:
      branch:
        - feature/*
      event:
        - push

  - name: build test image (build)
    image: plugins/kaniko
    settings:
      build_args:
        - COMMIT_SHA=${DRONE_COMMIT_SHA}
        - COMMIT_AUTHOR_EMAIL=${DRONE_COMMIT_AUTHOR_EMAIL}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - test
      repo: gitea.dxas90.xyz/dxas90/learn
      registry: gitea.dxas90.xyz
      expand-repo: false
    depends_on:
      - Run chart-testing (lint)
      - UnitTest (test)
    when:
      branch:
        - develop
      event:
        - push

  - name: build staging image (build)
    image: plugins/kaniko
    settings:
      build_args:
        - COMMIT_SHA=${DRONE_COMMIT_SHA}
        - COMMIT_AUTHOR_EMAIL=${DRONE_COMMIT_AUTHOR_EMAIL}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
      repo: gitea.dxas90.xyz/dxas90/learn
      registry: gitea.dxas90.xyz
      expand-repo: false
    depends_on:
      - Run chart-testing (lint)
      - UnitTest (test)
    when:
      branch:
        - master
      event:
        - push

  - name: build production image (build)
    image: plugins/kaniko
    settings:
      build_args:
        - COMMIT_SHA=${DRONE_COMMIT_SHA}
        - COMMIT_AUTHOR_EMAIL=${DRONE_COMMIT_AUTHOR_EMAIL}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_TAG}
      repo: gitea.dxas90.xyz/dxas90/learn
      registry: gitea.dxas90.xyz
      expand-repo: false
    depends_on:
      - build staging image (build)
    when:
      event:
        - tag
