---
kind: pipeline
type: kubernetes
name: golang

metadata:
  namespace: default
  annotations:
    drone-ci: "true"
  labels:
    drone-ci: "true"

clone:
  depth: 50

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
      - printf "go-%s\n" $(git describe --tags --always --dirty) > .tags

  - name: build Go image
    image: ghcr.io/finitum/drone-kaniko:0.7.0
    settings:
      skip_tls_verify: false # set to true for testing registries ONLY with self-signed certs
      build_args:
        - COMMIT_SHA=${DRONE_COMMIT_SHA}
        - COMMIT_AUTHOR_EMAIL=${DRONE_COMMIT_AUTHOR_EMAIL}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: library/learn
      dockerfile: docker/go.dockerfile
      registry: harbor.dxas90.xyz

image_pull_secrets:
  - dockerconfig

trigger:
  branch:
    - master
    - feature/*
  event:
    - push
