---
kind: pipeline
type: kubernetes
name: golang

metadata:
  namespace: default
  annotations:
    drone-ci: "true"
  labels:
    drone-ci: "true"

clone:
  depth: 50

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
      - printf "go-%s" $(git describe --tags --always --dirty) > .tags

  - name: build Go image
    image: banzaicloud/drone-kaniko
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: harbor.dxas90.xyz/library/learn
      dockerfile: docker/go.dockerfile
      registry: harbor.dxas90.xyz

image_pull_secrets:
  - dockerconfig

trigger:
  branch:
    - master
    - feature/*
  event:
    - push
