kind: pipeline
type: docker
name: default

environment:
  LAST_COMMIT_HASH: "$${DRONE_COMMIT_SHA::7}"
  APP_NAME: learn
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: "0"

steps:
- name: test
  image: golang:1.14-alpine
  commands:
    - "go test"

- name: build
  image: golang:1.14-alpine
  commands:
    - go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o main .

- name: publish
  image: "plugins/docker"
  settings:
    repo: "${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}"
    tags: ["latest"]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: docker.io

- name: parse
  image: dxas90/drone-kubectl
  commands:
    - export LAST_COMMIT_HASH="$${DRONE_COMMIT_SHA::7}"
    - envsubst < k8s/deployment.yaml > k8s/deployment_new.yaml

- name: deliver
  image: dxas90/drone-kubectl
  settings:
    kube_config:
      from_secret: kube_config
  commands:
    - env | sort
    - cat /tmp/config
    - echo ${PLUGIN_KUBE_CONFIG} | base64 -d
    # - kubectl apply -f k8s/deployment_new.yaml -n drone
trigger:
  event:
  - push
