# https://docs.gitlab.com/ee/ci/yaml/includes.html
include:
  - project: dxas90/learn
    file: .gitlab-ci-template.yml

stages:
  - test
  - build
  - containerize

test-code:
  stage: test
  extends: .go-test

build-branch:
  stage: build
  extends: .go-build
  except:
    - master

build:
  stage: build
  extends: .go-build
  only:
    - master

containerize:
  stage: containerize
  extends: .dockerize
    #  only:
    #    - master
