apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - ./deployment-patch.yaml
  - ./ingress-patch.yaml

resources:
  - ../../base/

images:
  - name: dxas90/learn
    newTag: latest

commonLabels:
  owner: gitops
  app: gitops-k8s
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
    team: DevOps
  annotations:
    note: generated
