version: 2.1
orbs:
  kaniko-publish: dxas90/kaniko-publish@dev:0.0.1
jobs:
  check_and_build_only:
    docker:
      - image: "glenathan/circleci-kaniko:build-62"
    working_directory: /workspace
    steps:
      - checkout
      - kaniko-publish/check:
          registry: harbor.dxas90.xyz
      - kaniko-publish/build_and_push:
          registry: harbor.dxas90.xyz
          dockerfile: go.dockerfile
          path: docker
          image: library/${CIRCLE_PROJECT_REPONAME}
          deploy: false
workflows:
  build_without_publishing:
    jobs:
      - check_and_build_only:
          context: learn
      - kaniko-publish/publish:
          context: learn
          registry: harbor.dxas90.xyz
          dockerfile: go.dockerfile
          path: docker
          image: library/${CIRCLE_PROJECT_REPONAME}
          requires:
            - check_and_build_only
