version: 2.1

orbs:
  kaniko-publish: glenjamin/kaniko-publish@0.0.4

workflows:
  build_and_publish:
    jobs:
      - kaniko-publish/publish:
          context: learn
          registry: harbor.dxas90.xyz
          dockerfile: docker/go.dockerfile
          image: library/${CIRCLE_PROJECT_REPONAME}
