apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-learn
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
        app: learn
        env: {{ .Values.labels.env }}
        cluster: {{ .Values.labels.cluster }}
  template:
    metadata:
      labels:
        app: learn
        env: {{ .Values.labels.env }}
        cluster: {{ .Values.labels.cluster }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-learn
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imageConfig.pullPolicy }}
        ports:
          - name: {{ .Chart.Name }}-web
            containerPort: {{ .Values.service.targetPort }}
            protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
