apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-learn
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: learn
        env: {{ .Values.labels.env }}
        cluster: {{ .Values.labels.cluster }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-learn
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imageConfig.pullPolicy }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
