kind: Secret
apiVersion: v1
metadata:
  name: {{ include "learn.fullname" . }}-secret
  labels:
{{ include "learn.labels" $ | indent 4 }}
data:
  APP_ENV: cHJvZA==
  APP_SECRET: ZTM4MWNkMGYiMTl5ODIyMw==
type: Opaque
