apiVersion: v1
kind: Service
metadata:
  name: {{ include "learn.fullname" . }}
  labels:
{{ include "learn.labels" $ | indent 4 }}
{{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Release.Name }}-learn
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Chart.Name }}-web
  selector:
{{ include "learn.labels" $ | indent 4 }}
