apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: learn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: https://github.com/dxas90/learn.git
    targetRevision: HEAD
    path: guestbook
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: learn
