apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./base

commonLabels:
  app: gitops-k8s
  owner: gitops
generatorOptions:
  annotations:
    note: generated
  disableNameSuffixHash: false
  labels:
    team: DevOps
    type: generated
