---
apiVersion: v1
kind: ConfigMap
metadata:
  name: learn-config
data:
  REDIS_DSN: redis://redis:6379?timeout=0.5
  MONGODB_URL: mongodb://mongodb:27017
  MAILER_URL: smtp://mail-server:1025
  LAST_COMMIT_HASH: "${LAST_COMMIT_HASH}"
