---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learn
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-traefik
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - app.dxas90.xyz
      secretName: app-dxas90-xyz-prod
  rules:
    - host: app.dxas90.xyz
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: learn
                port:
                  name: web

