---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: learn
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: dummy.dxas90.xyz
      http:
        paths:
          - path: /
            backend:
              serviceName: learn
              servicePort: web
