---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: learn-rollout
spec:
  replicas: 2
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: learn
  strategy:
    canary:
      stableService: learn-stable
      canaryService: learn-canary
      canaryMetadata:
        annotations:
          role: canary
        labels:
          role: canary
      stableMetadata:
        annotations:
          role: stable
        labels:
          role: stable
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 30
      - pause: {duration: 30s}
      - setWeight: 60
      - pause: {duration: 30s}
      - setWeight: 100
      - pause: {duration: 10}
