apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - ./deployment-patch.yaml
  - ./ingress-patch.yaml

resources:
  - ../../base/

images:
  - name: dxas90/learn
    newTag: test

commonLabels:
  app: gitops-k8s
  owner: gitops
generatorOptions:
  annotations:
    note: generated
  disableNameSuffixHash: true
  labels:
    team: DevOps
    type: generated
