---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: learn
  annotations:
    kubernetes.io/ingress.class: kong
    cert-manager.io/cluster-issuer: letsencrypt-staging
    konghq.com/override: https-only
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: staging-learn.dxas90.xyz
